### ISSUE TITLE
Needed example or docs for standard procedure on multiple getters

### ISSUE THREAD

**Issue by ausshir** [LiamBindle/PyVESC#5]
When using more than one getter the incoming buffer can get a bit messy, and simply decoding it directly and naively doesn't always get the intended message.

This applies specifically to turning on the encoder output (which is a periodic message) as well as requesting values (which is a triggered message).

Potentially, this could be a new feature - or it could be already implemented in a non-obvious way that I'm not seeing!

**Comment by LiamBindle** [comment]
I see what you're saying. Yeah that sounds like a good idea. Right now I think this could be accomplished by checking the the responses ID.

What I was thinking this would look like would be the following where the user has defined some handler, `user_defined_handler`, which they call with any parsed messages.

```python
response, consumed = pyvesc.decode(buff)
buff = buff[consumed:]

if response:
    user_defined_handler(id=response.id, msg=response)    # response.id should always be valid so long as resonse is not None
```
So far the focus of PyVESC has been solely on facilitating the encoding/decoding of messages according to the VESC message protocol. I was kind of hoping to keep it this way because I think it then provides a flexible and reliable base for developing VESC applications. I think that we would lose some generality of the library if we started implementing handlers.

Personally I think that this would be a really good feature but I don't think that PyVESC is the proper place to put it. 

What do you think?

**Comment by pythonmobile** [comment]
Liam: I just installed and ran the examples on PyVesc. Worked flawlessly! I have the hal sensors connected to the Vesc. How can I read the rotation position using pyvesc?

**Comment by LiamBindle** [comment]
@pythonmobile
Hey glad to hear it worked!

I think that Austin, @ausshir, might be a bit better suited to answer this question. I have primarily been working on the communication protocol rather than the actual VESC's themselves. @ausshir can you chime in?

**Comment by pythonmobile** [comment]
@ausshir Hope you already have a decoder for encoder somewhere.

@LiamBindle Thanks. Is the following code already checked in and ready to use for users?
``
response, consumed = pyvesc.decode(buff)
buff = buff[consumed:]

if response:
    user_defined_handler(id=response.id, msg=response) 
''

**Comment by LiamBindle** [comment]
Hey @pythonmobile 
Sorry for the late response. The code snippet I have shown above is just an example of how I would handle multiple getters. There are a lot of different ways this could be done (the example is just a simple one) but I don't want to restrict PyVESC to just one of these methods. I'd really like to keep this library general so I'm leaving it up to the users to implement their own.

Just as a reference this would be how I would do it (quick solution).

```python
# handler for GetValues
def get_values_callback(msg):
    # type(msg) is GetValues
    # handle the message however you'd like here
    print("Received a GetValues message")

# handler for GetRotorPosition
def get_rotor_position_callback(msg):
    # type(msg) is GetRotorPosition
    # handle the message however you'd like here
    print("Received a GetRotorPosition message") 

# make a list of callbacks to hold callbacks for id's between 0-35 (I've chosen 36 arbitrarily) 
callbacks = [None]*36  
callbacks[GetValues.id] = get_values_callback
callbacks[GetRotorPosition.id] = get_rotor_position_callback
```
Now wherever you parse the messages from your UART I'd put something like this
``` python
# buff is the UART read buffer
response, consumed = pyvesc.decode(buff)
buff = buff[consumed:]

# call the appropriate callback
callbacks[response.id](response)
```
This is a start on how I would do this. I have not tested this code but this would be how I would approach the problem. Essentially the idea is to have a list of callback functions which take the message as a parameter. The appropriate callback is indexed by messages ID.

Let me know if you have any problems!
