### ISSUE TITLE
Documentation missing type information. 

### ISSUE THREAD

**Issue by tlalexander** [LiamBindle/PyVESC#7]
I am having trouble with SetCurrent and I noticed it didn't mention what the units or data types are. It throws an error when I try to use a float, but float is what I would want to use. Integer values don't seem to work either. 

I noticed on dutycycle the example shows a value of 255, which makes me wonder if that is a 0-255 type of value rather than the float the docs suggest.

**Comment by LiamBindle** [comment]
I haven't used this message and I didn't write it but I was talking with @ottopasuuna and I believe this should be an integer in mA (ie. 0.6A should be given as int(600)). I'll update the documentation once I we figure out how it was supposed to be passed.

If that doesn't work could you post the error message and the call stack?

**Comment by LiamBindle** [comment]
**Update**:

Yes the units for SetCurrent are milliamps and the type should be an integer. Sorry about the confusion.
For example this should work:

```python
current = 1300 # [mA]
msg = pyvesc.SetCurrent(current)
pyvesc.encode(msg)
b'\x02\x05\x06\x00\x00\x05\x14`\xc5\x03'
```

@tlalexander Let me know if you have any further problems with this.

Relevant VESC code:
https://github.com/vedderb/bldc_uart_comm_stm32f4_discovery/blob/master/bldc_interface.c#L532
https://github.com/vedderb/bldc_uart_comm_stm32f4_discovery/blob/3cef7bab0a85100f2442f5652731b7e56a6051ac/buffer.c#L55

**Comment by tlalexander** [comment]
Awesome, thanks for the quick reply! Excited to test now as current mode works better for me. I tried it up to SetCurrent(100) but not high enough that it should have done anything. I will test this week and re open the issue if I have further problems.
