### ISSUE TITLE
CAN Bus Forwarding

### ISSUE THREAD

**Issue by jk213509** [LiamBindle/PyVESC#8]
Nice work, everyone. Was wondering if you have considered integrating the ability to forward messages over CAN (e.g., using the COMM_FORWARD_CAN byte) for communication with multiple VESCs. Or is this something I missed?

**Comment by LiamBindle** [comment]
Hi Justin,

Personally, I haven't look at this. I just took a quick look at the VESC documentation, and I agree that this would be a useful and fit well within the scope of PyVESC. Unfortunately I haven't worked with CAN-BUS before, and I'll be pretty busy over the next couple months, so I don't think that I'd be the right person to implement this. If someone else was inclined to implement this, I'd be more than happy to review and merge it into PyVESC though!

I'm going to mark Issue #8 as an open feature request in the mean time.

**Comment by jk213509** [comment]
Do you have a link to the message specs/structure?

**Comment by LiamBindle** [comment]
Yeah, [this page](http://vedder.se/2015/10/communicating-with-the-vesc-using-uart/) has some pretty good documentation of the protocol. I also see that CAN is discussed on it a bit as well.

Some of the details are a bit fuzzy in which case you might need to take a look at the actual official source code which you can find [here](https://github.com/vedderb/bldc_uart_comm_stm32f4_discovery).

Hope that helps and let me know if you need a hand with anything.

**Comment by LiamBindle** [comment]
Closed with PR #9.
